### ISSUE TITLE
好喜欢这个主题，能推出多个配色版本吗？

### ISSUE THREAD

**Issue by Dllragon** [sumruler/typora-theme-phycat#13]
这个主题太好用了！我一直想找一个简约的，标题层级清晰的主题，终于找到了！！！
顺带把你的网站安利给了一位物理老师
作者能多开发几组配色吗哈哈(蓝色调绿色调之类的)，感激不尽！

**Comment by sumruler** [comment]
有这个计划的，后面有时间整理一下，设计一下暗色模式，增加几套好看配色

**Comment by Dllragon** [comment]
谢谢作者！夏天橙黄色看着热热的哈哈哈

**Comment by sumruler** [comment]
已经完成！
