### ISSUE TITLE
对于代码块的一个建议

### ISSUE THREAD

**Issue by tuf612** [sumruler/typora-theme-phycat#15]
代码块可以小小的修改一下变成下面这种样式：
![IMG_20240908_153721](https://github.com/user-attachments/assets/3324d2b3-5247-4428-b8fc-cbf764adc0a3)
![IMG_20240908_153738](https://github.com/user-attachments/assets/3eec477b-18ea-422e-a202-607457bfc58c)

在红黄绿三个圆圈那一行加上所使用的语言的大写英文。

这样的话阅读的时候，对于代码块中的代码可以一眼看出所使用的语言及语法高亮。

**Comment by sumruler** [comment]
很好的想法，感谢建议，已经修改发布
