### ISSUE TITLE
YAML Front Matter的样式与phycat主题的样式不协调

### ISSUE THREAD

**Issue by tuf612** [sumruler/typora-theme-phycat#16]
与正文的各种效果比起来，YAML Front Matter的效果并不明显，或者说并没有什么css效果，导致在文档中使用YAML块时整体看起来会很突兀。

话说回来，我提了很多问题都差不多被作者给解决了，作者真是厉害，我要给你点个赞👍🏻👍🏻👍🏻👍🏻

**Comment by sumruler** [comment]
可以截个图吗？我没怎么使用过YAML Front Matter所以没设置它的样式

**Comment by sumruler** [comment]
已经为Yaml增加了样式，样式比较简单没有好的思路，后面有好的想法再修改更新
