### ISSUE TITLE
大佬,请问一下这是为什么啊?

### ISSUE THREAD

**Issue by Eulus209** [sumruler/typora-theme-phycat#18]
typora版本为1.9.4,使用了"https://github.com/obgnail/typora_plugin"这个插件,目前测试为四五级标题是会分开显示.
<img width="1280" alt="64e3e9aed3d0a9741d5b869a4040485" src="https://github.com/user-attachments/assets/5134f37f-5af6-415a-b5b9-de3326102455">
<img width="1280" alt="fd697a073d15c2215d97315ac327bda" src="https://github.com/user-attachments/assets/7eee6efa-49d8-4c82-914f-5f9c23467ce3">

**Comment by sumruler** [comment]
> typora版本为1.9.4,使用了"[https://github.com/obgnail/typora_plugin"这个插件,目前测试为四五级标题是会分开显示](https://github.com/obgnail/typora_plugin%22%E8%BF%99%E4%B8%AA%E6%8F%92%E4%BB%B6,%E7%9B%AE%E5%89%8D%E6%B5%8B%E8%AF%95%E4%B8%BA%E5%9B%9B%E4%BA%94%E7%BA%A7%E6%A0%87%E9%A2%98%E6%98%AF%E4%BC%9A%E5%88%86%E5%BC%80%E6%98%BE%E7%A4%BA). <img alt="64e3e9aed3d0a9741d5b869a4040485" width="1280" src="https://private-user-images.githubusercontent.com/144452824/385823023-5134f37f-5af6-415a-b5b9-de3326102455.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MTI2NDQsIm5iZiI6MTczMTUxMjM0NCwicGF0aCI6Ii8xNDQ0NTI4MjQvMzg1ODIzMDIzLTUxMzRmMzdmLTVhZjYtNDE1YS1iNWI5LWRlMzMyNjEwMjQ1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxNTM5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjczZDhhNWYxYzI3MjdjZWIxYjFjN2ZkMjE3NTUzZjUwY2FhNGU4ZTIzYjg1NTg1ZDJjYzYxNTc4MDNmZGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UT0J-qS24ar6N3rshoJad-tD1fiv9hSd1gqnJ-6JutI"> <img alt="fd697a073d15c2215d97315ac327bda" width="1280" src="https://private-user-images.githubusercontent.com/144452824/385823047-7eee6efa-49d8-4c82-914f-5f9c23467ce3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MTI2NDQsIm5iZiI6MTczMTUxMjM0NCwicGF0aCI6Ii8xNDQ0NTI4MjQvMzg1ODIzMDQ3LTdlZWU2ZWZhLTQ5ZDgtNGM4Mi05MTRmLTVmOWMyMzQ2N2NlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxNTM5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWI1NzQzMTY5NDY3M2Q0MGE1MzlmNTEwMzI4MGI2Y2ExODA4OGE1OGNhOGY4ZGM5MDhhZmMyNmQ5ZGUzM2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cHhKK4Bl3cu4GBSuO5-5XoBZoDO4rZhnNd2Cu2NGtTE">

可能是与某些样式冲突，你可以逐个插件开关试一下，看看是哪个插件冲突

**Comment by Eulus209** [comment]
好的ヽ(￣▽￣)و,感谢大佬,找到冲突位置了,是原本那个插件的auto_number有问题,关掉就好了!
![image](https://github.com/user-attachments/assets/e7be72ab-846c-4d55-80e2-797b1ea696d9)
