### ISSUE TITLE
能否支持一下图片并排

### ISSUE THREAD

**Issue by z-soulx** [sumruler/typora-theme-phycat#19]
能否支持一下图片并排

**Comment by sumruler** [comment]
> 能否支持一下图片并排

这个好像没办法从主题实现吧，你可以插入一个表格，然后在表格中插入图片实现并排效果

**Comment by z-soulx** [comment]
> > 能否支持一下图片并排
> 
> 这个好像没办法从主题实现吧，你可以插入一个表格，然后在表格中插入图片实现并排效果

可以的，[Drake](https://github.com/liangjingkanji/DrakeTyporaTheme) 这个主题支持，效果如下
<img width="1084" alt="图片" src="https://github.com/user-attachments/assets/52b593d1-f2bf-4635-97ea-680493e03867">

**Comment by sumruler** [comment]
> > > 能否支持一下图片并排
> > 
> > 
> > 这个好像没办法从主题实现吧，你可以插入一个表格，然后在表格中插入图片实现并排效果
> 
> 可以的，[Drake](https://github.com/liangjingkanji/DrakeTyporaTheme) 这个主题支持，效果如下 <img alt="图片" width="1084" src="https://private-user-images.githubusercontent.com/38135909/394173493-52b593d1-f2bf-4635-97ea-680493e03867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTg1NzQsIm5iZiI6MTczMzgxODI3NCwicGF0aCI6Ii8zODEzNTkwOS8zOTQxNzM0OTMtNTJiNTkzZDEtZjJiZi00NjM1LTk3ZWEtNjgwNDkzZTAzODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA4MTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZTNmNjk3MzYxMDA4NTFlMjAxNWI2YjUyYmYxMDQ4MDM4N2Q5ZGJkYTcxZDMxYTU1ZjNhN2EzNTJmMjk4YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5L5K7YAzpzkzDWLiomplKr8ibK4KCQKNADDviMWDT0w">

好的我学习一下，如果可行我就更新上来

**Comment by sumruler** [comment]
> > > 能否支持一下图片并排
> > 
> > 
> > 这个好像没办法从主题实现吧，你可以插入一个表格，然后在表格中插入图片实现并排效果
> 
> 可以的，[Drake](https://github.com/liangjingkanji/DrakeTyporaTheme) 这个主题支持，效果如下 <img alt="图片" width="1084" src="https://private-user-images.githubusercontent.com/38135909/394173493-52b593d1-f2bf-4635-97ea-680493e03867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTg1NzQsIm5iZiI6MTczMzgxODI3NCwicGF0aCI6Ii8zODEzNTkwOS8zOTQxNzM0OTMtNTJiNTkzZDEtZjJiZi00NjM1LTk3ZWEtNjgwNDkzZTAzODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA4MTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZTNmNjk3MzYxMDA4NTFlMjAxNWI2YjUyYmYxMDQ4MDM4N2Q5ZGJkYTcxZDMxYTU1ZjNhN2EzNTJmMjk4YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5L5K7YAzpzkzDWLiomplKr8ibK4KCQKNADDviMWDT0w">

能给出Markdown的片段吗？这个图片并排的语法是什么？

**Comment by z-soulx** [comment]
> > > > 能否支持一下图片并排
> > > 
> > > 
> > > 这个好像没办法从主题实现吧，你可以插入一个表格，然后在表格中插入图片实现并排效果
> > 
> > 
> > 可以的，[Drake](https://github.com/liangjingkanji/DrakeTyporaTheme) 这个主题支持，效果如下 <img alt="图片" width="1084" src="https://private-user-images.githubusercontent.com/38135909/394173493-52b593d1-f2bf-4635-97ea-680493e03867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTg1NzQsIm5iZiI6MTczMzgxODI3NCwicGF0aCI6Ii8zODEzNTkwOS8zOTQxNzM0OTMtNTJiNTkzZDEtZjJiZi00NjM1LTk3ZWEtNjgwNDkzZTAzODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA4MTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZTNmNjk3MzYxMDA4NTFlMjAxNWI2YjUyYmYxMDQ4MDM4N2Q5ZGJkYTcxZDMxYTU1ZjNhN2EzNTJmMjk4YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5L5K7YAzpzkzDWLiomplKr8ibK4KCQKNADDviMWDT0w">
> 
> 好的我学习一下，如果可行我就更新上来

幸苦，刚从drake转过来，自己尝试过，就是没效果，对前端知识还是业务

**Comment by z-soulx** [comment]
图片并列

- <img src="./image/4630f7f22f5f408d37c9b8a483c64940.png" alt="测试1" style="zoom: 25%;" /><img src="./image/4630f7f22f5f408d37c9b8a483c64940.png" alt="测试2" style="zoom:25%;" />
- <img src="./image/4630f7f22f5f408d37c9b8a483c64940.png" alt="测试1" style="zoom: 25%;" />

**Comment by sumruler** [comment]
> 图片并列
> 
> * ![测试1](./image/4630f7f22f5f408d37c9b8a483c64940.png)![测试2](./image/4630f7f22f5f408d37c9b8a483c64940.png)
> * ![测试1](./image/4630f7f22f5f408d37c9b8a483c64940.png)

好的，已解决问题，等我解决一下其它问题然后尽快在下一个版本更新出来

**Comment by z-soulx** [comment]
感谢，期待下个版本

**Comment by sumruler** [comment]
已解决，更新到最新
