### ISSUE TITLE
有序列表不连续情况下，显示异常

### ISSUE THREAD

**Issue by Nedved-liao** [sumruler/typora-theme-phycat#2]
显示所有标题都是1了
![image](https://github.com/sumruler/typora-theme-phycat/assets/35453327/10cceeb8-f4b2-43a0-a7fd-15658f331809)
markdown写法如下
![image](https://github.com/sumruler/typora-theme-phycat/assets/35453327/ac8644aa-7b59-447a-b5fa-b54d87dd1756)

**Comment by sumruler** [comment]
你好，这个好像是Markdown特性，建议解决的方法：
1. 有序列表那一行输入后按shift+enter键换行；
2. 可以先把所有的列表项输入完成，然后使用shift+enter换行来详细编辑描述各个列表项。
如果此方案可行可关闭此issue，如果不可行或者有修改建议，请继续跟进
