### ISSUE TITLE
疑惑：图片并排比例，比例缺失有点严重？期望：尽最大的努力更大的百分比也能并排

### ISSUE THREAD

**Issue by z-soulx** [sumruler/typora-theme-phycat#20]
- 背景：展示同一张图片。
  - drake主题：两个25%的图片会并排。
  - cat现状：两个 25%不会并排，zoom调整为22%后才会并排。
- 期望 ：
  - 尽最大的努力更大的百分比也能并排，typroa快捷缩放图片最低是25%。 

- 感谢博主图片并排功能的更新

**Comment by sumruler** [comment]
> * 背景：展示同一张图片。
>   
>   * drake主题：两个25%的图片会并排。
>   * cat现状：两个 25%不会并排，zoom调整为22%后才会并排。
> * 期望 ：
>   
>   * 尽最大的努力更大的百分比也能并排，typroa快捷缩放图片最低是25%。
> * 感谢博主图片并排功能的更新

没搞明白你的意思，我这边测试效果是一样的，不存在切换主题变化显示效果会变化。你能说详细点吗？最好给出Markdown的代码。贴个文件上来。

**Comment by sumruler** [comment]
> * 背景：展示同一张图片。
>   
>   * drake主题：两个25%的图片会并排。
>   * cat现状：两个 25%不会并排，zoom调整为22%后才会并排。
> * 期望 ：
>   
>   * 尽最大的努力更大的百分比也能并排，typroa快捷缩放图片最低是25%。
> * 感谢博主图片并排功能的更新

而且这个东西应该和你原先的图片大小有关吧，你换个图片效果又不一样了

**Comment by z-soulx** [comment]
背景： 个人对两个图片并排功能的精益求精的期望，能够方便快速缩放后的并排操作。【鸡蛋挑骨头需求的请教】
example： 
- 原图：<img width="1017" alt="4630f7f22f5f408d37c9b8a483c64940" src="https://github.com/user-attachments/assets/f60f00b3-cc6e-4a25-aaa8-ec620fefc8df" />
- `<img src="./demo原图.png" alt="测试1" style="zoom: 25%;" /><img src="./demo原图.png" alt="测试1" style="zoom: 25%;" />`

现状：缩放25%，两个图片不会并排，只有手动调到22%才行。 比如Drake主题，25%的时候就可以并排在一起。
期望：将最大努力将缩放比例大的图片并排在一起。尽可能的让图片并排，比如该图片25%也能并排，甚至50%也能并排。
原因：1 官方提供的快捷缩放最小是25%，否则要手动更改  2 在并排效果的前提下，尽最大努力展示大图。

**Comment by sumruler** [comment]
我明白你的意思了，这个和页面宽度有关，你自己调一下吧，你打开phycat文件夹，找到phycat.light.css文件打开，把第45行改成1260px应该可以满足你的要求，不行就再调大一点。
![Clip_2024-12-12_14-25-17](https://github.com/user-attachments/assets/0f400cf3-ca55-41ca-8fbe-f4b4a265b3fb)

**Comment by z-soulx** [comment]
感谢，这样我的排版就能无缝切换了。👍
