### ISSUE TITLE
代码块字体不是等宽

### ISSUE THREAD

**Issue by witt-bit** [sumruler/typora-theme-phycat#21]
我已将主题发布到ArchLinux  AUR仓库

https://aur.archlinux.org/packages/typora-theme-phycat

目前有两个问题
> 我不清楚是不是Linux环境导致的

1.代码块字体不是等宽字体
![image](https://github.com/user-attachments/assets/d9d25b1c-e896-425d-8783-1481dc532501)

2.行内代码光标选中时，断断续续的
![image](https://github.com/user-attachments/assets/c1f3cd7a-4153-4607-bf2b-1358f8bf3b2e)

**Comment by sumruler** [comment]
问题1 确实有点问题，我修复一下；
问题2 是样式问题，我也思考一下怎么修复

**Comment by sumruler** [comment]
问题1已修复
问题2样式特性，不影响使用，不去解决了。

**Comment by witt-bit** [comment]
已更新到1.2.1   https://aur.archlinux.org/packages/typora-theme-phycat


提两个建议
1.麻烦为本仓库添加开源license协议（如果你愿意的话），毕竟已分发到了其他平台

2.我个人推荐使用[Monaco](https://github.com/Karmenzind/monaco-nerd-fonts)这款字体

**Comment by sumruler** [comment]
添加了开源协议，代码字体就不改了，你可以自己换一下满足你的需求
