### ISSUE TITLE
导出PDF出现了文字截断

### ISSUE THREAD

**Issue by beijingmonkey** [sumruler/typora-theme-phycat#3]
![image](https://github.com/sumruler/typora-theme-phycat/assets/14816907/d36a71d1-7598-4468-88e3-2872e4f77a80)

**Comment by sumruler** [comment]
我已经做了优化尝试修复这个问题，请重新拉取代码测试，如果问题解决请关闭此Issue，如果未解决可以继续回复，也可以把你的markdown文件发送到我的邮箱sumruler@qq.com，以便我来调试一下。
