### ISSUE TITLE
在已有二级标题的上下行，创建二级标题，会自动合并到已有的二级标题

### ISSUE THREAD

**Issue by wenyongda** [sumruler/typora-theme-phycat#7]
在已有二级标题的上下行，创建二级标题，会自动合并到已有的二级标题

**Comment by sumruler** [comment]
因为这套主题的二级标题是inline-block方式显示的，来让它的渐变色背景宽度与文字宽度一致，所以在连续两个二级标题时会让他们自动合为一行。
请尝试手动在两个二级标题间再插入一个换行符，来分割两个二级标题。
如果你不希望适应此习惯，可以在主题文件phycat.css的第83行将inline-block改为table
![Clip_2024-03-18_13-56-45](https://github.com/sumruler/typora-theme-phycat/assets/56953545/0a50fc5d-945c-4b1a-9e6a-6a8b6d1740a0)
这可能会适应你当前的习惯。但这可能会与https://github.com/sumruler/typora-theme-phycat/issues/6提出的问题冲突

**Comment by sumruler** [comment]
像是Lapis主题都会存在这样的问题。
