### ISSUE TITLE
有序标题里用无序标题没有显示

### ISSUE THREAD

**Issue by zRandomw** [sumruler/typora-theme-phycat#8]
有序标题里用无序标题没有显示

**Comment by zhaokai56789** [comment]
/* 无序列表整体样式 */
#write ul {
  list-style: none;
  padding-left: 6px !important;
}

#write ul li {
  position: relative;
  padding-left: 25px;
  line-height: 1.6rem;
}

#write ul li::before {
  content: "";
  width: 12px;
  height: 12px;
  background: #ffc840;
  display: inline-block;
  vertical-align: middle;
  margin-top: 10px;
  margin-right: 11px;
  margin-left: -24px;
  border-radius: 100%;
  border: 3px solid #fff;
  z-index: 100;
  position: absolute;
}

#write ul li::after {
  content: "";
  height: 100%;
  width: 2px;
  background: #ffc9401d;
  position: absolute;
  left: 6px;
  top: 20px;
}

#write ul li:last-child:after {
  display: none;
}

**Comment by sumruler** [comment]
更改了列表样式，去除花里胡哨，回归简洁直观
